echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"

echo "Hello, Good morning!"
echo "We are learning Github and Git"
echo "Happy Mahashivratri all of you"
echo "This changes are done by Prajwal"
echo "its 27.02.2025 today"
echo "Hello I have made the change plesase check bedore merge"
echo "Change done on 28.02.2025 at 21.04"

echo "I am working in REQ092348"
echo "Adding new data"
echo "I am DevOps-2"
echo "THE DevOps engineer one and only Smit"
