echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"
echo "Hello, Good morning!"
echo "We are learning Github and Git"
echo "Happy Mahashivratri all of you"
echo "This changes are done by Prajwal"
echo "its 27.02.2025 today"
echo "Heyy Smit, I have bulid this code check it once before deployment"
echo "Btw how you are feeling right now after talking with her."